version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'github-actions'
    reviewers:
      - 'jerome-benoit'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      regular:
        update-types:
          - 'patch'
          - 'minor'
      eslint:
        update-types:
          - 'major'
        patterns:
          - 'eslint'
          - '@eslint/*'
      commitlint:
        patterns:
          - '@commitlint/*'
    labels:
      - 'dependencies'
    reviewers:
      - 'jerome-benoit'
    versioning-strategy: increase
